REST_SERVER_PORT: 3000
REST_SERVER_WRITE_TIMEOUT_MS: 1000
REST_SERVER_READ_TIMEOUT_MS: 1000

GRPC_SERVER_PORT: 3001
GRPC_REQUEST_TIMEOUT_MS: 1000

FLAGR_HOST: http://localhost:18000
FLAGR_BASE_PATH: http://localhost:18000/api/v1